version: '3.8'

services:
  api:
    image: bertilvossebelt/oog-api:latest
    container_name: oog-api
    ports:
      - "5000:80"
    restart: unless-stopped

  webclient:
    image: bertilvossebelt/oog-webclient:latest
    container_name: oog-webclient
    ports:
      - "4000:80"
    restart: unless-stopped
    depends_on:
      - api

networks:
  default:
    name: oog-network